# Generated by Django 3.2.13 on 2024-02-13 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0002_series_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='genre',
        ),
        migrations.AddField(
            model_name='series',
            name='genres',
            field=models.ManyToManyField(to='series.Genre'),
        ),
    ]
