# Generated by Django 3.2.13 on 2024-02-13 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0003_auto_20240213_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='series',
            old_name='genres',
            new_name='genre',
        ),
    ]
