# Generated by Django 3.2.13 on 2024-02-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0004_rename_genres_series_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='imdb_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='quick_summary',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='release_year',
            field=models.IntegerField(default=2022),
        ),
        migrations.AddField(
            model_name='series',
            name='seasons',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='series',
            name='thoughts',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
